# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3143a8a2bb73441185d238accaba0af4981e3fd3f125f81d7b087906f2753d9eef4f6b8cd31ad4891d826bbd70b3b83c130f0752d0ec507911806a69e643e02

test:
  secret_key_base: 7e37275354b3ee618417d4b059fcfe29898d4bdab3d9482758d28846750f2825731214841501ac35fded82ecddf5e050bf8de104d065f38fedf5f837749829c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
