# Generated by Django 2.0.4 on 2018-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.TextField()),
                ('desc', models.TextField()),
                ('star', models.IntegerField()),
                ('detaildesc', models.TextField()),
                ('totalstar', models.IntegerField()),
                ('fork', models.IntegerField()),
                ('watch', models.IntegerField()),
            ],
        ),
    ]
