# Generated by Django 2.0.4 on 2018-06-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendrepo',
            name='star',
            field=models.IntegerField(null=True),
        ),
    ]
