# Generated by Django 2.0.4 on 2018-06-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trendrepo',
            old_name='detaildesc',
            new_name='detail_desc',
        ),
        migrations.RenameField(
            model_name='trendrepo',
            old_name='totalstar',
            new_name='total_star',
        ),
    ]
