# Generated by Django 2.0.4 on 2018-06-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_trendrepo_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendrepo',
            name='star',
        ),
        migrations.AddField(
            model_name='trendrepo',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
