# Generated by Django 2.0.5 on 2018-07-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.TextField()),
                ('desc', models.TextField()),
                ('star', models.IntegerField()),
                ('detail_desc', models.TextField()),
                ('total_star', models.IntegerField()),
                ('fork', models.IntegerField()),
                ('watch', models.IntegerField()),
            ],
        ),
    ]
