# Generated by Django 2.0.5 on 2018-07-07 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubtrend',
            old_name='repo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='githubtrend',
            old_name='star',
            new_name='today_star',
        ),
    ]
