# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eurecaSummerIntrern' do
	pod 'SwiftyJSON', '~> 4.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for eurecaSummerIntrern

  target 'eurecaSummerIntrernTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eurecaSummerIntrernUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
